---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: Redhat.yml
  when: ansible_os_family == "Redhat"

- name: Start tomcat service
  service:
    name: tomcat{{ tomcat_version }}
    state: started
    enabled: yes
